ansible_host: ENC[AES256_GCM,data:CvXijJwuaex3F6ypP+Ss,iv:qFoE4koY16g+/Ef5cG34ZlGnaJjXMOmbNcqDzR7RLt8=,tag:zWPbqxQDeOek6Yw3ZSY6aA==,type:str]
proxmox_vmid: ENC[AES256_GCM,data:9cie,iv:s0T6vI+96lPlM2MxeBMfBVreW6Jg9OkmYh7BxgNOEsY=,tag:1gKPIe31Nu+TfUmE72Evog==,type:int]
lxc_base_service_user: ENC[AES256_GCM,data:Ycv6LU0=,iv:Yh4D2qRRKtSmAM1ZtJ8rU14hIq8HNKLHQmse/GHZ2iU=,tag:ZSR7fdtkbnDDRZkVYUfO9Q==,type:str]
lxc_caddy_caddyfile_content: ENC[AES256_GCM,data:sF1oHG927WxlA16tmV6CaAUn1Smw471qEO9i5bnNGLpLuGWj5yPekKMUrEzl88+1g/0rCHjLaCKkQRyI/Gk3S3+P00u/1IuItQxSBYvN8k25UqczXSVF2vNkfX56DbR5u8efrviCyGRu4ZVOKWc2FB42dOgBZuQK+RlK0v5oqN4hg2yPFHnbG73AT8WbDOQssUf2xVQkM1J7BwrN00gH5Myxp617FhhKrLD+/gdauWAs0nm6i+jPkfm6JT1QbSOpS7vTHSsVwvak1UmF89QBlPo2Vb2W14edrc4HuiejrAC+QFd0JKlZ2kDj04AIVFeBfngqQYKnFfNNVh37JLj4WLIAH/tQvo4xGm7ip+xtEOm3tnW5+bLMYWjJLjvDr1W6YZlQlVx4GdE2J/RZKBMU21YOoJAlHqlJcIqGHhIJ5CLr97vgrp3v14hoAIQSjjhsUSOpEZdej8sbi2r/OitOEW9E8LXZdTpLTsbcOez6f4AX/6mx98+JlX+rgrmb1emEIYROZpV0r4yHXncle+ltuJ9LQpGTRboaFVVxFjioxFASG3gP/HfVK4wIEXrY1RMz+2wvndFsWQD0aEp9WFJrLuiRpx0Kfb+50wXbLR4a+UUCtDHUH6mDHj8Z8KX3E56bKqwBpsiyhChmFa81sutkEzcV493XWR75ZVEjzfdgZJ0g+98T1Bqod8j3JBQbl9Pu+shpz4/8pMqnyLy1FMmho+Mu55mCfbdToG7kqla1zRRr+HnmHw==,iv:qlL3DnJyjPl/SZ0J9q02DjmnkjEWhZarOpSJEMGvu7s=,tag:5dMpWraxmofz9EtqfdtHgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VXkxRDdWaVA5dkFUdmY1
            d2JQUExtOTNwZXFkaE1HSitjRWdqK3ZONlhNCnFrVzJKclhURlg2K2VGWGNkQzlw
            cHljTUx3ci9oOU10YWtpQ1VZdXVuQlEKLS0tIFNPMHMwTS9mR1YvZVpFYVRJTFdo
            QVF5ZERpUURZcTVMd014QjgxVXBWVWMKvDTzskag6+vlFKHPPVTfiOa2LSYaFaBQ
            6Iu1BZ6yrivq/H1pLIDLlxOQLljqZo4rsOVLuQAUEI4ucdBtV/Yd5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T04:14:06Z"
    mac: ENC[AES256_GCM,data:Qc6RtQR9UApKB4yONdZa9TUxKR6LtU6rSxWcASv2bQxgEdlLo3sjEPZMo8akBZLzyrX5bta3HKRdN20lSEBKuuaIEB3uvuSERFGahsTfRkpmqZKky4zczOoMUL1ojE/LISwLASi4rHrqr8BkfNQI4oLS8D+eqeyGsL5z7PE9YOo=,iv:776xvF7dgrXMUA1k+r3SRi3tSq6iuz/0LqzSdnCMIZw=,tag:WF+CE5WQ761D3Q7mnNRboA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
