ansible_host: ENC[AES256_GCM,data:uuekRS5lZVBScxitCdOs,iv:awN/BQw6c8IqwYmPbuctpCiMcF5+Kc02wfpdpJWdtUg=,tag:Fqtqirt4ffPur13eFxkwmA==,type:str]
proxmox_vmid: ENC[AES256_GCM,data:QT0r,iv:+lCAl5sc8mpcUosaftdS/HHIsoA4l8Y5rvQ+Zqoqkx8=,tag:RoGwdzEru+Z7j/r5oIZsMw==,type:int]
lxc_base_service_user: ENC[AES256_GCM,data:gLbgq5w=,iv:3EuvLY19dN89dwy0cuHAKeAgM9CDPNKSThjR7+q9fAI=,tag:pl816TORP9wSsIBmgsjvUA==,type:str]
lxc_caddy_caddyfile_content: ENC[AES256_GCM,data:7OEAz3Ky2PUSjROfyeLu5PZpwPqaU4hT8+BPe9+Db88uavYiU/mFlIIRAiIPmpcCtmvz1qQpJ4bp8rH5mcYRuZBG,iv:gQd7OJpejhpqMGgum+1RNIO8AtDGowhIzpKLXXXw53I=,tag:ThwfMHps+G6BaYhm4nfcPQ==,type:str]
sops:
    age:
        - recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOY2NBcHljY3ZKQTNMYjhO
            Vm1UU0JCUW01ZjZJWW9LdHFySGJ6dFVLV3lRCmszd2YzMThHRTMvMGxiSHk1a0ZI
            Zm44OXFUVjNJZldDZ3dHY1ZUdll2NUEKLS0tIGtiaTYwU1RnSm15VkYzejVLcURx
            aEtyN2RlaGNVZlpNRVVqVmVSdmpPdUUKSZZZarcC6vknwG/ey7P1iE1HV3OjWB7q
            nj3gdVOgcNUYVYT01TyhIezTppl9Jg7KkBNeiCIu4JZ47/nsouYMcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T15:47:36Z"
    mac: ENC[AES256_GCM,data:v5RS6U5tRvnKSjE7FFoCQKrzYlmCz8iCooTCn1KZhe2B/LWVx5eKrMY/DYv/n4hH3NW5OKgKfqwr2sAyV+vQaX1lHV2WF6MBUEU9dn6GIowk+QY0AZKvHXuOArESqS0P2SKXOs4zA1uSA4IyWCfA9aV7MHxcJbnmo6UqWU++Org=,iv:VAvx2ItVwZxWgq5ClLuR8DdAocBt3WtVnKf7r8aHsVU=,tag:X6lZLo3k9mlahqEF26r50w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
