# SPDX-License-Identifier: CPAL-1.0
# Copyright (c) 2026 Aryan Ameri

- name: Reload networking
  ansible.builtin.command:
    cmd: ifreload -a
  changed_when: true

- name: Reload container DNAT rules
  ansible.builtin.command:
    cmd: nft -f /etc/nftables-container-dnat.conf
  changed_when: true
