# SPDX-License-Identifier: CPAL-1.0
# Copyright (c) 2026 Aryan Ameri

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Postmap sasl_passwd
  ansible.builtin.command:
    cmd: postmap /etc/postfix/sasl_passwd
  changed_when: true
  notify: Restart postfix

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Apply pending network changes
  ansible.builtin.command:
    cmd: pvesh set /nodes/{{ inventory_hostname }}/network
  changed_when: true
