# SPDX-License-Identifier: 0BSD
# Copyright (c) 2026 Aryan Ameri

proxmox_install_gpg_key_url: "https://enterprise.proxmox.com/debian/proxmox-archive-keyring-trixie.gpg"
proxmox_install_gpg_key_checksum: "sha256:136673be77aba35dcce385b28737689ad64fd785a797e57897589aed08db6e45"
proxmox_install_primary_interface: ""
proxmox_install_postfix_relayhost: ""
