ansible_host: ENC[AES256_GCM,data:tRBQN0ledVFAEf3LNcLV,iv:3APevjwZIDGTp6TeT74reFkJ4qNxIZI60rhFK6yaffc=,tag:TvAvDj4ozMRBmgGppV9p6w==,type:str]
proxmox_vmid: ENC[AES256_GCM,data:uspS,iv:40GkNgkvkyw0R4DeRMh2+rm1nSfNnq1+/dbiLqJ6SbE=,tag:i4YJNku6PZCpr23nyPljtg==,type:int]
lxc_base_service_user: ENC[AES256_GCM,data:82MknKewHjc=,iv:z5XQP+5Zq2wrXCOQ+1ukXdwluunwgwV/l9mC6jZIEJU=,tag:QR2YtsJqyqo/zjFm0TLorg==,type:str]
lxc_wallabag_domain_name: ENC[AES256_GCM,data:9lEonfd1WRhFMo7PCAyG+g3hHX7McFIVkkeHwQ4=,iv:QAlGJIg2kC2BwgybczTZKAHSUadTUlJ4mZDfjWmeQW8=,tag:hVVL7wfsDVB/zh3+6okCXQ==,type:str]
lxc_wallabag_secret: ENC[AES256_GCM,data:JheemL9YWRtvvy1mUqOFOqd2fYrELkRzBWFNLbpsNt0=,iv:ydnFVyEaRMLA8cjTdDtFiWu+ZAd8+GrNDxzfJ8q+GY4=,tag:Xsr6PSIJE2vhoOeu7FY17g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTkdYQ2RBSWg5ajVoUFFE
            TWdGN0xnQ2pjM3JKdVhMdStsUGZZMiswOXk4CllpUWlVMTJaV0ZkVXpZQm9RSzY2
            dnVTNzlxdEUxcDBDekllM0hLaGN5T3cKLS0tIDhqdGIwbmJlLy9Bd3NuQUdtaDUv
            WXJCTU05VUpWdDZKaEdSbGIrVzNaZTAK79FQyLJwRuoiVF9XkJ/aukiUoeyjVrP0
            Kxta6PNRk1TxgcFAvIj/qi1V8yMbjWys6iUxQ4xmAcdbMcv5fsE+Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T03:50:53Z"
    mac: ENC[AES256_GCM,data:vnNyssqrYF5KvUSdBdkqeJris+NAPYAVMNDoGGFhG67Ct5c9rLpLZKpWq8A/zy+GoZBzhEo7NYUVA0sCTSiAShqei+ZUnSEcTv4ZFfb0I7ymgA4b4d08KXcgZKpI+f3BerlML/qeXyZGzY4A//Gt++wG1/XMOxgLs3eA4Wke5AY=,iv:PUPUo+bwY7lBUI1qpr/bqapeklrLtCvUz0U6n57P9cU=,tag:+XqwUxr/G5cjvUFv80d8TQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
