ansible_user: ENC[AES256_GCM,data:WB8KsA==,iv:2J37sSeajVSKjHZw0IcaaJrbwymdXhjFCsFa5CP0068=,tag:oBqFhs+mSb445kihTGTOVw==,type:str]
sops:
    age:
        - recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdEc3TytnSGhtTWhnTWFp
            dHdxS0FXSjZsM0pqZExnSzI5TjhZcDdwZ2tnCklTSDVnS2ZURHBmOFFiVUs0MUU2
            bFVDYll4RzFKU0E4RzZiMnlzZk5uS28KLS0tIGNKcFdHZmhJY21WNkprekJGMCsw
            eEtRS1Avam13eWxvRjk5RFRZWFE3MDQKjfLi1SjbddgI2DHZhtM62ftqQ0qoBa2B
            iQi4rzvx5nZ9cusoAK/a3PiqcGCExgZEc4x1PVI1JOnHPe41AtWNeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T15:47:35Z"
    mac: ENC[AES256_GCM,data:iC7xLEMmQgGBAZrAdIZ3kokcw+O7Bo72BwQbAXl8zRbXzLpAwal7yUahAShHSzTbHZviweQqFe4xcagWm9Y7S+S6tgCWo2niG5eLzl3oX9Gnx/LUX1wmh5fR4tBFbjS9L49JiVwJaO9RfdvAIczXwrdSSUFPGC78lLyERCvhM1I=,iv:+Z/ZDKUxTWhMrvjTVuCe/BiicoIbrohHIk8/fxYtBsY=,tag:jeCULEZQmZA3x5+j5V2ogQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
