# SPDX-License-Identifier: CPAL-1.0
# Copyright (c) 2026 Aryan Ameri

- name: Configure Wallabag container
  hosts: wallabag
  gather_facts: false
  roles:
    - role: lxc_preflight
    - role: lxc_base
    - role: lxc_wallabag
  tags: [wallabag]
